repos:
  - repo: local
    hooks:
      - id: generate-index
        name: Generate index
        entry: bash .git-hooks/generate_index_and_check.sh
        language: system
        pass_filenames: false
        files: ^
